Addressing #14 Documentation
meet59patel/schooler pull request #17
Opened 2020-10-02 11:42 UTC by godslayer201

Description - 
Added how to contribute
Added issue template
Added feature enhancement template
OS - Windows 10

2020-10-02 19:27 UTC, meet59patel requested changes

2020-10-02 19:27 UTC, meet59patel commented on Contributing.md
> +git clone https://github.com/meet59patel/schooler
This would clone my repo. Actually the contributor has to clone his forked repo, so change URL to `https://github.com/<your-username>/schooler.git`

2020-10-02 19:27 UTC, meet59patel commented on Contributing.md
> +- Before creating bug reports, please gp through this list .
Fix the typo here: "please **go** through"

2020-10-03 03:51 UTC, godslayer201 commented on Contributing.md
> +git clone https://github.com/meet59patel/schooler
Changes done

2020-10-03 03:52 UTC, godslayer201 commented on Contributing.md
> +- Before creating bug reports, please gp through this list .
Changes done

2020-10-03 21:18 UTC, meet59patel approved these changes
LGTM 👍🏻

2020-10-03 21:19 UTC, meet59patel commented
Good job on your first contribution to Schooler @godslayer201 👍🏻

2020-10-03 21:19 UTC, merged

2020-10-03 21:21 UTC, meet59patel commented
This PR closes #14

2020-10-03 21:22 UTC, meet59patel commented
give @godslayer201 25 points