Dynamic rendering of Recently Accessed files
meet59patel/schooler pull request #32
Opened 2020-10-13 18:29 UTC by Aniruddhmuley2001

@meet59patel @HemangNakarani 
Have added the functionality as expected from issue #11 . The recently accessed documents are dynamically rendered, using React Functional Components.

Issue faced: In the present scenario, I could not generate the clickable link in the filename section. But will it work if another Column for the link is created?

2020-10-14 20:13 UTC, meet59patel requested changes
Great work, especially you got the point of using another object for temporarily showing the data 💯
This would be helpful when we fetch data from Backend as I've explained earlier.

Just fix the typo and I'll merge the PR 😄

2020-10-14 20:13 UTC, meet59patel commented on src/components/dashboard/RecentlyAccessed.js
> +const RecentlyAccesed = () => {
Can you just fix this minor typo of `RecentlyAccessed` ?
The same change would go in the last line of same file - at `export default` part

2020-10-14 20:31 UTC, meet59patel commented
@Aniruddhmuley2001 regarding your links doubt: Try doing something like this: 

- 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/45785817/96041843-14aba100-0e8a-11eb-83eb-83359734960c.png">
- 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/45785817/96041866-1e350900-0e8a-11eb-941c-f5ec20addb9f.png">

I'll prefer if the links are there like this.

2020-10-15 05:39 UTC, Aniruddhmuley2001 commented
Have made the required changes.
Feature added: The file in the table will open on a different tab, without compromising with the ESLint property of jsx-no-target-blank property of the whole file, by disabling it only for one line in RecentlyAccessed.js, filling the file name in the table.

2020-10-15 20:50 UTC, meet59patel approved these changes
Great going! 🚀

2020-10-15 20:50 UTC, merged

2020-10-15 20:54 UTC, meet59patel commented
give @Aniruddhmuley2001 25 points