Showing List of friends online
meet59patel/schooler pull request #35
Opened 2020-11-18 14:09 UTC by Aniruddhmuley2001

This PR will be solving issue #12 . Here, 3 columns created under headings 'Photo', 'Name', and 'Status'. Also, this has been implemented by creating an object for details of friends, so as to have a dynamic implementation.

@meet59patel Please do review the PR, and suggest the required changes.

2020-11-18 14:33 UTC, meet59patel requested changes

2020-11-18 14:33 UTC, meet59patel commented on src/views/Index.js
> +  picture: "https://lh5.googleusercontent.com/-c_qI1qFUiqI/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnU4NATEYF2mFRLBtU2XOFfLnIgFw/s96-c/photo.jpg",
These profile picture links come with expiry, just like the Google_Token, so these might not even be available the next day we open it. For now just use one of the images in assets folder for this purpose.

Great thing that you used such a dummy object for table data like I had mentioned before 💯

2020-11-18 14:42 UTC, meet59patel commented
give @Aniruddhmuley2001 5 points

2020-11-18 15:50 UTC, Aniruddhmuley2001 commented
@meet59patel Have updated the picture links in the object. But as of now to display the images in the Photo column, have kept a constant image, since I could not figure out a way to dynamically render a local file, without it being stored in a database or cloud (rather getting a URL for the image). But I believe, this won't affect the project since at the end, we will be receiving images as a URL or link, which can easily be integrated.

2020-11-19 08:46 UTC, meet59patel approved these changes
All Good! 💥

2020-11-19 08:47 UTC, merged