Updated Meta tags and favicon
meet59patel/schooler pull request #6
Opened 2020-10-01 02:30 UTC by helloshantanu

Updated Meta Tags and Favicon for the App.

Used Standard SEO Techniques to Boost site performance on Search.

I Have Added Your Email in meta tags as meet59patel@gmail.com, if this ismt your email, please update and Merge request

2020-10-01 08:51 UTC, meet59patel requested changes
Just update email and I'll merge.

2020-10-01 08:51 UTC, meet59patel commented on public/index.html
> +    <meta property="og:email" content="meet59patel@gmail.com" />
My email is patelmeet59@gmail.com
Commit the change please.

2020-10-01 08:51 UTC, meet59patel commented
@helloshantanu Thanks a lot for the PR. But keep in mind that you won't be getting SLoP points for contributions to any project other than your assigned one. 
Good work on this.

2020-10-01 08:53 UTC, helloshantanu commented
My project hasn't opened any issue yet, so hanging around contributing to others😅

2020-10-01 08:55 UTC, meet59patel commented
> My project hasn't opened any issue yet, so hanging around contributing to others😅

Alright, makes sense. I just had to clarify about SLoP points though.

2020-10-02 09:10 UTC, meet59patel commented
@helloshantanu looks like there's somewhere a little typo that is breaking whole site. Check out the deployment of your PR at https://schooler-eafi0wnhv.vercel.app/  (from View deployment button above)
<img width="498" alt="image" src="https://user-images.githubusercontent.com/45785817/94907015-20c45580-04bd-11eb-99c6-be7f2d681224.png">

The entire site just loads blank.

2020-10-02 09:12 UTC, helloshantanu commented
Fixing it right away

2020-10-02 19:19 UTC, meet59patel commented
@helloshantanu Looks like the site breaking issue is fixed 👍🏻
But in the latest commit you've added `package-lock.json` file, which shouldn't be there actually as we're using `Yarn` for this project. So `yarn.lock` file is already there. This may create issues with some of the deployment platforms. Can you simply delete `package-lock.json` and commit? I'll be able to merge after that. 

Great work otherwise 👍🏻

2020-10-03 00:02 UTC, helloshantanu commented
Ok, will do that

2020-10-03 20:48 UTC, meet59patel approved these changes
LGTM 👍🏻

2020-10-03 20:48 UTC, merged

2020-10-04 14:04 UTC, meet59patel commented
Fixes #5